services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServerConnection=Server=mssql;Database=WeatherForecastDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      - mssql

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests  
    volumes:
      - ./TestResults:/app/TestResults  
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
